version: '3'
services:
  hwww:
    build: ./web
    ports:
    - "80:80"
    depends_on:
    - db
    environment:
    - DATABASE_HOST=db
    - PORT=80
    volumes:
    - ./web:/app
  db:
    build: ./db